gsd:
  image: alankent/gsd:0.3
  ports:
    - "80:80"
    - "3000:3000"
    - "3001:3001"
    - "135:135"
    - "139:139"
    - "445:445"
    - "2222:22"
  environment:
    - SAMBA_START=1
  volumes:
    - ~/.composer:/home/magento/.composer
